class Email:
    TERM_OPEN = 'TERM_OPEN'
    TERM_EDITED = 'TERM_EDITED'
    BOOKED = 'BOOKED'
    SWITCH_BROADCAST = 'SWITCH_BROADCAST'
    SWITCH = 'SWITCH'
    SWITCHED = 'SWITCHED'
    UNBOOKED_IN_30_DAYS = 'UNBOOKED_IN_30_DAYS'
    UPCOMING_7_DAYS = 'UPCOMING_7_DAYS'
    SUMMONED = 'SUMMONED'

class DayType:
    VIKARIE_DAG = 'vikariedag'
    ARBETS_DAG = 'arbetsdag'
